repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.92.3
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
        args:
          - --args=--init
      - id: terraform_docs
        args:
          - --args=--lockfile=false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-merge-conflict
