name: terraform-validate

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      branch:
        type: string
        required: true

jobs:
  validate:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      ARM_CLIENT_ID: ${{ vars.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ vars.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}
      ARM_USE_OIDC: true
      TF_IN_AUTOMATION: true
      TF_VAR_admin_password: ${{ secrets.WINDOWS_ADMIN_PASSWORD }}
      PROJECT_DIR: .
      ENV_DIR: environments/${{ fromJSON('{"DEV":"dev","UAT":"uat","PROD":"prod"}')[inputs.environment] }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5
      - name: Install TFLint
        run: curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      - run: terraform fmt -check -recursive ${{ env.PROJECT_DIR }}
      - run: terraform -chdir=${{ env.ENV_DIR }} init -backend=false -input=false
      - run: terraform -chdir=${{ env.ENV_DIR }} validate
      - run: tflint --init && tflint --chdir=${{ env.ENV_DIR }}
